export const GET_RESTOMENU_REQUEST = "GET_RESTOMENU_REQUEST";
export const GET_RESTOMENU_SUCCEED = "GET_RESTOMENU_SUCCEED";
export const GET_RESTOMENU_FAILED = "GET_RESTOMENU_FAILED";

export const GET_RESTOMENUBYRESTO_REQUEST = "GET_RESTOMENUBYRESTO_REQUEST";
export const GET_RESTOMENUBYRESTO_SUCCEED = "GET_RESTOMENUBYRESTO_SUCCEED";