export const GET_RESTOSHOP_REQUEST = "GET_RESTOSHOP_REQUEST";
export const GET_RESTOSHOP_SUCCEED = "GET_RESTOSHOP_SUCCEED";
export const GET_RESTOSHOP_FAILED = "GET_RESTOSHOP_FAILED";

export const GET_RESTOSHOPBYID_REQUEST = "GET_RESTOSHOPBYID_REQUEST";
export const GET_RESTOSHOPBYID_SUCCEED = "GET_RESTOSHOPBYID_SUCCEED";